### ISSUE TITLE
Error after upgrading to php 5.4

### ISSUE THREAD

**Issue by ThinkWired** [michael-e/email_template_manager#92]
When I try to submit a form I get this warning "Symphony Deprecated Warning: Non-static method Email::create() should not be called statically, assuming $this from incompatible context"

about this line " $email = Email::create();"

Should this extension work in php 5.4?

**Comment by michael-e** [comment]
PHP 5.4? Are you sure? This PHP version is old (and unsupported, AFAIK). You should really use PHP 5.6!

Is this warning output to the frontend? Generally this should not happen with Symphony, because Symphony sets PHP's error reporting in order to only output real errors (not warnings) in the frontend.

Which version of Symphony do you use?

That said, ideally this warning should not occur at all. I will take a look.

**Comment by michael-e** [comment]
@ThinkWired, can you "hack" a very simple change into your Symphony version and see if it works? Here it is:

https://github.com/symphonycms/symphony-2/pull/2691/commits/6db0077ef06c755bc483655bc3247cec0be56333

(This is supposed to go into Syphony 2.7.0.)

**Comment by ThinkWired** [comment]
That fixed it. Thank you.
