### ISSUE TITLE
Member role page level permissions problem

### ISSUE THREAD

**Issue by wdebusschere** [michael-e/email_template_manager#97]
I have an email template that sends a pdf attachement(with the pdf extention, pagetype pdf).

Members with a specific role can send this email template.
In order for this to work, I need to give page level permissions to this confidential page to the member role public.

Expected behaviour:  
Only page level permissions for this role.

**Comment by michael-e** [comment]
I don't really understand. What do you mean by "In order for this to work" – what is "this"? And what is "this confidential page"? A page that generates the PDF file? Or a page that has a save event with an ETM email filter attached to it?

I also don't understand the expected behaviour. Please try and describe your issue more precisely.

**Comment by wdebusschere** [comment]
Michael,
 The attachment comes from a page with pagetype pdf, this page is confidential. So member role public has no access. When i set page level permissions for role public to no access, the attached pdf is the login page. When i give access for member role public to this pdf page, the pdf is in the mail.. Thank you.

**Comment by michael-e** [comment]
So the PDF is generated dynamically by Symphony, as a Symphony page?

I am afraid that this is "by design". ETM has no Member role, so it can only fetch attachments (pages) which are accessible for the "public" role.

Do you want the PDF to be "protected", somehow? Then I only see some sort of "token" solution. For example, ETM can use POST data as params (https://github.com/michael-e/email_template_manager/pull/61), so you might POST a secret token which is then used to build the PDF's URL.

**Comment by wdebusschere** [comment]
Ok, thank you for the explanation and solution!

**Comment by michael-e** [comment]
You're welcome!
